# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a07a9b5950a066da016946dbda4962ce2844b87c4de7d4e03eee694af3eeae64cb578d4400d69069647a2ab48a75081cc8107daa4ec2651b06287b289d0768de

test:
  secret_key_base: 3d1b41d3ab2d425634827cc4ce71fb8ce448b8bb4dd84578dde363ab9bd13992b891116176f95a01ba219b35c92875d0daf3b6085ff6020d4b8394bc95331790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
